### PR TITLE
RFC: macOS compatibility

### PR DESCRIPTION
**Pull request by Smattr**
This PR contains changes necessary to run Halfempty on macOS 10.13.6.

This tool surfaced just at a crucial time that I needed to do some non-trivial test case minimization, so firstly thank you :)

While I think the commits in this PR are relatively fine-grained and well explained, this patch series admittedly conflates several things:
* hiding or providing alternatives for Linux-isms
* suppressing compiler warnings
* Clang compatibility

Specifically I think it's worth calling out the following suboptimal things:
* on non-Linux, `sendfile` is now a read-then-write loop. Apart from being less efficient I find this logic quite fiddly, so did I get it right?
* on non-Linux, children do not get `SIGKILL`ed automatically. Offhand I don't know how to implement this in a portable way.
* on non-Linux, ASLR is left enabled. I'm not sure how to cleanly implement this on macOS, though as I indicated in my commit message there may be a trick to borrow from GDB here.

I only lightly tested this by using it to minimize the example use case I had on hand. In particular I didn't test any of the dot/monitor functionality as I didn't need it and didn't know what exactly I should look for when testing. Please let me know if there's specific things I should test or if you'd like these commits edited.

### CODE REVIEW

**Comment by taviso** [comment]
Thanks so much for doing this, I'm surprised the biggest changes needed were just working around `sendfile()` and `splice()`.

Let me see if I can setup mac testing so that I don't accidentally break it in future, and then I see no reason not to merge this. Maybe if I finish working on a configure script it would be better to automatically add a `splice_generic.c` and a `sendfile_generic.c` for non-Linux.

**Comment by taviso** [comment]
I have a mac machine for testing now, timeouts don't seem to work but the other tests seem to pass, nice!

I think I'd rather have the sendfile and splice replacements separate, and add them in the Makefile, like

```make
ifeq ($(shell uname),Darwin)
EXTRA	= sendfile_gen.o splice_gen.o
endif
``` 

Then add `$(EXTRA)` to halfempty dependencies. WDYT?

**Comment by Smattr** [comment]
Sorry, this is partly on me, as I noticed timeouts didn't work but for some reason I thought this was expected in the default configuration. Now that I look into it, I think the problem is differing semantics of `setpgid` between Linux and macOS. In its manpages, macOS has only this to say:

> setpgid() sets the process group of the specified process pid to the specified pgid.  If pid is zero, then the call applies to the current process.

IOW, passing `0` as the `pgid` has no special treatment. It looks like the usage in halfempty is relying on the PGID ending up as the inverse of the child's PID so that we can then kill the entire process group by `-pid`. Not sure of how best to remedy this. Store the PGID in the child struct? But we also need to somehow pick a PGID...

----

The `$(EXTRA)` design works for me, but we would still need some ifdefery to decide which one to call, right? I guess we could just name the implementations in *_gen.c as `splice` and `sendfile`, but that makes me nervous of namespace clashes if Apple were to ever implement these in future.

**Comment by taviso** [comment]
So sorry for the slow response, I was away last week. Hmm, does that mean it just wants `setpgrp()` instead?

Huh, I just tried it, and that seems to fix it. That was easy :smile: 

It looks like the `siginfo_t` fields are filled in slightly different for `WNOHANG` children from `waitid`, but it seems to be fine just to remove the assertion. Then the timeout testcase passes for me, nice.

If you make those changes, I'll apply...WDYT?

**Comment by taviso** [comment]
Ah, I was getting occasional failures in the tests - it looks like might need to `#ifdef` out the `g_debug()` in the signal handler as well, because that doesn't seem thread safe on Mac. With that removed, the tests seem quite reliable on my test system.

**Comment by taviso** [comment]
Let's just do it, I'll fix up the Makefile changes. Thanks so much Matthew!

**Pull request merged**
